/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package elportaldeguille;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.Arrays;
import javafx.scene.paint.Color;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Guille
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
        this.setLocationRelativeTo(null);
        jAreaDatos.setEditable(false);
    
    }
    
    public void expNombre() {
        if (jTextNombre.getText().matches("[a-zA-Z]{25}") && 
                jTextApellidos.getText().matches("[a-zA-Z]{15} [a-zA-Z]{15}") &&
                jTextEdad.getText().matches("[0-9]{2}") &&
                jTextCiudad.getText().matches("[a-zA-Z]{25}") &&
                jTextProvincia.getText().matches("[a-zA-Z]{25}") &&
                jTextPais.getText().matches("[a-zA-Z]{25}") &&
                jTextCP.getText().matches("[0-9]{5}") &&
                jTextNomUsuario.getText().matches("[a-zA-Z0-9]{32}")) {
            jTextNombre.setText(jTextNombre.getText());
            jTextApellidos.setText(jTextApellidos.getText());
            jTextEdad.setText(jTextEdad.getText());
            jTextCiudad.setText(jTextCiudad.getText());
            jTextProvincia.setText(jTextProvincia.getText());
            jTextPais.setText(jTextPais.getText());
            jTextCP.setText(jTextCP.getName());
            jTextNomUsuario.setText(jTextNomUsuario.getText());
        } else {
            int opcion = JOptionPane.showConfirmDialog(null, "HOLA", "Error", 0);
            jTextNombre.setText(Integer.toString(opcion)); 
            jTextApellidos.setText(Integer.toString(opcion));
            jTextEdad.setText(Integer.toString(opcion));
            jTextCiudad.setText(Integer.toString(opcion));
            jTextProvincia.setText(Integer.toString(opcion));
            
            
                    
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTitulo = new javax.swing.JPanel();
        jTitulo = new javax.swing.JLabel();
        jPanelDatos = new javax.swing.JPanel();
        jNombre = new javax.swing.JLabel();
        jApellidos = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jTextApellidos = new javax.swing.JTextField();
        jEdad = new javax.swing.JLabel();
        jTextEdad = new javax.swing.JTextField();
        jGenero = new javax.swing.JLabel();
        jRadioVaron = new javax.swing.JRadioButton();
        jRadioMujer = new javax.swing.JRadioButton();
        jPais = new javax.swing.JLabel();
        jTextPais = new javax.swing.JTextField();
        jCiudad = new javax.swing.JLabel();
        jTextCiudad = new javax.swing.JTextField();
        jProvincia = new javax.swing.JLabel();
        jTextProvincia = new javax.swing.JTextField();
        jCP = new javax.swing.JLabel();
        jTextCP = new javax.swing.JTextField();
        jNomUsuario = new javax.swing.JLabel();
        jTextNomUsuario = new javax.swing.JTextField();
        jPassword = new javax.swing.JLabel();
        jTextPass = new javax.swing.JTextField();
        jPanelInfoImpresa = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jAreaDatos = new javax.swing.JTextArea();
        jButtonImprimir = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanelTitulo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "TITULO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N

        jTitulo.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jTitulo.setForeground(new java.awt.Color(102, 102, 102));
        jTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTitulo.setText("REGISTEITOR");
        jTitulo.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanelTituloLayout = new javax.swing.GroupLayout(jPanelTitulo);
        jPanelTitulo.setLayout(jPanelTituloLayout);
        jPanelTituloLayout.setHorizontalGroup(
            jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTituloLayout.setVerticalGroup(
            jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos Personales:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 1, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        jNombre.setBackground(new java.awt.Color(255, 255, 255));
        jNombre.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jNombre.setForeground(new java.awt.Color(102, 102, 102));
        jNombre.setText("Nombre:");

        jApellidos.setBackground(new java.awt.Color(255, 255, 255));
        jApellidos.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jApellidos.setForeground(new java.awt.Color(102, 102, 102));
        jApellidos.setText("Apellidos:");

        jTextNombre.setBackground(new java.awt.Color(102, 102, 102));
        jTextNombre.setForeground(new java.awt.Color(255, 255, 0));
        jTextNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextNombreFocusLost(evt);
            }
        });

        jTextApellidos.setBackground(new java.awt.Color(102, 102, 102));
        jTextApellidos.setForeground(new java.awt.Color(255, 255, 0));

        jEdad.setBackground(new java.awt.Color(255, 255, 255));
        jEdad.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jEdad.setForeground(new java.awt.Color(102, 102, 102));
        jEdad.setText("Edad:");

        jTextEdad.setBackground(new java.awt.Color(102, 102, 102));
        jTextEdad.setForeground(new java.awt.Color(255, 255, 0));
        jTextEdad.setText("00");
        jTextEdad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextEdadFocusGained(evt);
            }
        });

        jGenero.setBackground(new java.awt.Color(255, 255, 255));
        jGenero.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jGenero.setForeground(new java.awt.Color(102, 102, 102));
        jGenero.setText("Genero:");

        jRadioVaron.setBackground(new java.awt.Color(255, 255, 255));
        jRadioVaron.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jRadioVaron.setForeground(new java.awt.Color(102, 102, 102));
        jRadioVaron.setText("VARÓN");
        jRadioVaron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioVaronActionPerformed(evt);
            }
        });

        jRadioMujer.setBackground(new java.awt.Color(255, 255, 255));
        jRadioMujer.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jRadioMujer.setForeground(new java.awt.Color(102, 102, 102));
        jRadioMujer.setText("MUJER");
        jRadioMujer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioMujerActionPerformed(evt);
            }
        });

        jPais.setBackground(new java.awt.Color(255, 255, 255));
        jPais.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jPais.setForeground(new java.awt.Color(102, 102, 102));
        jPais.setText("País:");

        jTextPais.setBackground(new java.awt.Color(102, 102, 102));
        jTextPais.setForeground(new java.awt.Color(255, 255, 0));

        jCiudad.setBackground(new java.awt.Color(255, 255, 255));
        jCiudad.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jCiudad.setForeground(new java.awt.Color(102, 102, 102));
        jCiudad.setText("Ciudad:");

        jTextCiudad.setBackground(new java.awt.Color(102, 102, 102));
        jTextCiudad.setForeground(new java.awt.Color(255, 255, 0));

        jProvincia.setBackground(new java.awt.Color(255, 255, 255));
        jProvincia.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jProvincia.setForeground(new java.awt.Color(102, 102, 102));
        jProvincia.setText("Provincia:");

        jTextProvincia.setBackground(new java.awt.Color(102, 102, 102));
        jTextProvincia.setForeground(new java.awt.Color(255, 255, 0));

        jCP.setBackground(new java.awt.Color(255, 255, 255));
        jCP.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jCP.setForeground(new java.awt.Color(102, 102, 102));
        jCP.setText("C.P:");

        jTextCP.setBackground(new java.awt.Color(102, 102, 102));
        jTextCP.setForeground(new java.awt.Color(255, 255, 0));
        jTextCP.setText("00000");
        jTextCP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextCPFocusGained(evt);
            }
        });
        jTextCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCPActionPerformed(evt);
            }
        });
        jTextCP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextCPKeyReleased(evt);
            }
        });

        jNomUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jNomUsuario.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jNomUsuario.setForeground(new java.awt.Color(102, 102, 102));
        jNomUsuario.setText("Nombre Usuario:");

        jTextNomUsuario.setBackground(new java.awt.Color(102, 102, 102));
        jTextNomUsuario.setForeground(new java.awt.Color(255, 255, 0));
        jTextNomUsuario.setText("Max.32 Caracteres");
        jTextNomUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextNomUsuarioFocusGained(evt);
            }
        });
        jTextNomUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextNomUsuarioMouseClicked(evt);
            }
        });

        jPassword.setBackground(new java.awt.Color(255, 255, 255));
        jPassword.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jPassword.setForeground(new java.awt.Color(102, 102, 102));
        jPassword.setText("Password:");

        jTextPass.setBackground(new java.awt.Color(102, 102, 102));
        jTextPass.setForeground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout jPanelDatosLayout = new javax.swing.GroupLayout(jPanelDatos);
        jPanelDatos.setLayout(jPanelDatosLayout);
        jPanelDatosLayout.setHorizontalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addComponent(jNombre)
                        .addGap(18, 18, 18)
                        .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jApellidos)
                        .addGap(18, 18, 18)
                        .addComponent(jTextApellidos))
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addComponent(jEdad)
                        .addGap(18, 18, 18)
                        .addComponent(jTextEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jGenero)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioVaron)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioMujer)
                        .addGap(18, 18, 18)
                        .addComponent(jPais)
                        .addGap(18, 18, 18)
                        .addComponent(jTextPais, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addComponent(jNomUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(jTextNomUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPassword)
                        .addGap(18, 18, 18)
                        .addComponent(jTextPass))
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addComponent(jCiudad)
                        .addGap(18, 18, 18)
                        .addComponent(jTextCiudad)
                        .addGap(18, 18, 18)
                        .addComponent(jProvincia)
                        .addGap(18, 18, 18)
                        .addComponent(jTextProvincia)
                        .addGap(18, 18, 18)
                        .addComponent(jCP)
                        .addGap(18, 18, 18)
                        .addComponent(jTextCP, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelDatosLayout.setVerticalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNombre)
                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jApellidos)
                    .addComponent(jTextApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEdad)
                    .addComponent(jTextEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jGenero)
                    .addComponent(jRadioVaron)
                    .addComponent(jRadioMujer)
                    .addComponent(jPais)
                    .addComponent(jTextPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCiudad)
                    .addComponent(jTextCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProvincia)
                    .addComponent(jTextProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCP)
                    .addComponent(jTextCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNomUsuario)
                    .addComponent(jTextNomUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPassword)
                    .addComponent(jTextPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelInfoImpresa.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Información Impresa:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 1, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        jAreaDatos.setBackground(new java.awt.Color(102, 102, 102));
        jAreaDatos.setColumns(20);
        jAreaDatos.setForeground(new java.awt.Color(255, 255, 255));
        jAreaDatos.setRows(5);
        jScrollPane1.setViewportView(jAreaDatos);

        javax.swing.GroupLayout jPanelInfoImpresaLayout = new javax.swing.GroupLayout(jPanelInfoImpresa);
        jPanelInfoImpresa.setLayout(jPanelInfoImpresaLayout);
        jPanelInfoImpresaLayout.setHorizontalGroup(
            jPanelInfoImpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoImpresaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanelInfoImpresaLayout.setVerticalGroup(
            jPanelInfoImpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jButtonImprimir.setBackground(new java.awt.Color(102, 102, 102));
        jButtonImprimir.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jButtonImprimir.setForeground(new java.awt.Color(255, 255, 0));
        jButtonImprimir.setText("IMPRIMIR TEXTO");
        jButtonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirActionPerformed(evt);
            }
        });

        jButtonLimpiar.setBackground(new java.awt.Color(102, 102, 102));
        jButtonLimpiar.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jButtonLimpiar.setForeground(new java.awt.Color(255, 255, 0));
        jButtonLimpiar.setText("LIMPIAR CAMPOS");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        jButtonGuardar.setBackground(new java.awt.Color(102, 102, 102));
        jButtonGuardar.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jButtonGuardar.setForeground(new java.awt.Color(255, 255, 0));
        jButtonGuardar.setText("GUARDAR INFO.");

        jMenu1.setText("Archivo");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelInfoImpresa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDatos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonImprimir)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonGuardar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelInfoImpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonImprimir)
                    .addComponent(jButtonLimpiar)
                    .addComponent(jButtonGuardar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNomUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextNomUsuarioMouseClicked
        jTextNomUsuario.setText("");
    }//GEN-LAST:event_jTextNomUsuarioMouseClicked

    private void jTextNomUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextNomUsuarioFocusGained
        jTextNomUsuario.setText("");
    }//GEN-LAST:event_jTextNomUsuarioFocusGained

    private void jButtonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirActionPerformed
        String Varon = null;
        String Mujer = null;
        if (jRadioVaron.isSelected()) {
            Varon = "Varon";
        } else {
            Varon = "";
        }
        if (jRadioMujer.isSelected()) {
            Mujer = "Mujer";
        } else {
            Mujer = "";
        }

        jAreaDatos.setText("Nombre ...: " + jTextNombre.getText() + "\n"
                + "Apellidos .: " + jTextApellidos.getText() + "\n"
                + "Edad ........: " + jTextEdad.getText() + "\n"
                + "Género ....: " + Varon + Mujer + "\n"
                + "País .........: " + jTextPais.getText() + "\n"
                + "Ciudad ....: " + jTextCiudad.getText() + "\n"
                + "Provincia .: " + jTextProvincia.getText() + "\n"
                + "C.P. ..........: " + jTextCP.getText() + "\n"
                + "Usuario ...: " + jTextNomUsuario.getText() + "\n"
                + "Pass ........: " + jTextPass.getText() + "\n");
    }//GEN-LAST:event_jButtonImprimirActionPerformed

    private void jRadioVaronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioVaronActionPerformed
        jRadioMujer.setSelected(false);
    }//GEN-LAST:event_jRadioVaronActionPerformed

    private void jRadioMujerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioMujerActionPerformed
        jRadioVaron.setSelected(false);
    }//GEN-LAST:event_jRadioMujerActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        jTextApellidos.setText("");
        jTextNombre.setText("");
        jTextEdad.setText("");
        jTextCiudad.setText("");
        jTextProvincia.setText("");
        jTextPais.setText("");
        jTextCP.setText("");
        jTextNomUsuario.setText("");
        jTextPass.setText("");
        jAreaDatos.setText("");
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jTextCPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCPKeyReleased

    }//GEN-LAST:event_jTextCPKeyReleased

    private void jTextCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCPActionPerformed

    private void jTextEdadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextEdadFocusGained
        jTextEdad.setText("");
    }//GEN-LAST:event_jTextEdadFocusGained

    private void jTextCPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextCPFocusGained
        jTextCP.setText("");
    }//GEN-LAST:event_jTextCPFocusGained

    private void jTextNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextNombreFocusLost
        expNombre();
    }//GEN-LAST:event_jTextNombreFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jApellidos;
    private javax.swing.JTextArea jAreaDatos;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JLabel jCP;
    private javax.swing.JLabel jCiudad;
    private javax.swing.JLabel jEdad;
    private javax.swing.JLabel jGenero;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel jNomUsuario;
    private javax.swing.JLabel jNombre;
    private javax.swing.JLabel jPais;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JPanel jPanelInfoImpresa;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JLabel jPassword;
    private javax.swing.JLabel jProvincia;
    private javax.swing.JRadioButton jRadioMujer;
    private javax.swing.JRadioButton jRadioVaron;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextApellidos;
    private javax.swing.JTextField jTextCP;
    private javax.swing.JTextField jTextCiudad;
    private javax.swing.JTextField jTextEdad;
    private javax.swing.JTextField jTextNomUsuario;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextPais;
    private javax.swing.JTextField jTextPass;
    private javax.swing.JTextField jTextProvincia;
    private javax.swing.JLabel jTitulo;
    // End of variables declaration//GEN-END:variables
}
